export const BASE = [
  {
    label: "Company Name",
    description: "Write the name of the company",
    category: "Base information",
    link: "https://www.google.com/search?q=",
    position: 1,
    type: "text",
  },
  {
    label: "Ticker",
    description: "For example GOOG or TSLA",
    category: "Base information",
    link: "https://www.google.com/search?q=",
    position: 2,
    type: "text",
  },
  {
    label: "Company Description",
    description: "Write a short description of the company",
    category: "Base information",
    link: "https://www.google.com/search?q=",
    position: 3,
    type: "textarea",
  },
  {
    label: "Sector",
    description: "For example banking, industry or commerce",
    category: "Base information",
    link: "https://www.google.com/search?q=",
    position: 4,
    type: "text",
  },
  {
    label: "Line of business",
    description:
      "For example internet banking, industrial machines or ecommerce",
    category: "Base information",
    link: "https://www.google.com/search?q=",
    position: 5,
    type: "text",
  },
  {
    label: "List",
    description: "Where can the company be bought?",
    category: "Base information",
    link: "https://www.google.com/search?q=",
    position: 6,
    type: "text",
  },
  {
    label: "Market Cap (MSEK)",
    description: "The total company value",
    category: "Pricing",
    link: "https://www.google.com/search?q=",
    position: 1,
    type: "number",
  },
  {
    label: "Stock Price",
    description: "How the market values the company",
    category: "Pricing",
    link: "https://www.google.com/search?q=",
    position: 2,
    type: "number",
  },
  {
    label: "Stock Currency",
    description: "What currency the stock is traded in",
    category: "Pricing",
    link: "https://www.google.com/search?q=",
    position: 3,
    type: "text",
  },
  {
    label: "P/E (Earning power)",
    description: "Price / Earnings",
    category: "Valuation",
    link: "https://www.google.com/search?q=",
    position: 1,
    type: "number",
  },
  {
    label: "P/S (Growth and size)",
    description: "Price / Sales",
    category: "Valuation",
    link: "https://www.google.com/search?q=",
    position: 2,
    type: "number",
  },
  {
    label: "P/B (Valuation of assets)",
    description: "Price / Book",
    category: "Valuation",
    link: "https://www.google.com/search?q=",
    position: 3,
    type: "number",
  },
  {
    label: "Yield ('Free' ROI)",
    description: "Return on investment without selling",
    category: "Valuation",
    link: "https://www.google.com/search?q=",
    position: 4,
    type: "number",
  },
  {
    label: "What is the company product? How do they earn money?",
    description: "Product",
    category: "Product & Market",
    link: "https://www.google.com/search?q=",
    position: 1,
    type: "text",
  },
  {
    label:
      "What is their unique selling point? Is there something that differentiates the company from the rest?",
    description: "USP",
    category: "Product & Market",
    link: "https://www.google.com/search?q=",
    position: 2,
    type: "text",
  },
  {
    label:
      "How big is the market for the product today? Is it a large and stable company?",
    description: "Market size / Stability",
    category: "Product & Market",
    link: "https://www.google.com/search?q=",
    position: 3,
    type: "text",
  },
  {
    label:
      "Do you think the market will shrink or grow in the coming five years? Why do you think so?",
    description: "Market growth",
    category: "Product & Market",
    link: "https://www.google.com/search?q=",
    position: 4,
    type: "text",
  },
  {
    label:
      "Who are the biggest competitors on the market? Are they bigger or smaller than the company?",
    description: "Competitors",
    category: "Product & Market",
    link: "https://www.google.com/search?q=",
    position: 5,
    type: "text",
  },
  {
    label:
      "What are your thoughts on the company management? Is their background/experience fit for expansion?",
    description: "Company management",
    category: "People",
    link: "https://www.google.com/search?q=",
    position: 1,
    type: "text",
  },
  {
    label:
      "Has the management achieved their goals over the last 5 years? What have they accomplished during the period?",
    description: "Management goal achievment",
    category: "People",
    link: "https://www.google.com/search?q=",
    position: 2,
    type: "text",
  },
  {
    label:
      "Is there a significant management ownership in the company? How large is it?",
    description: "Management ownership",
    category: "People",
    link: "https://www.google.com/search?q=",
    position: 2,
    type: "text",
  },
  {
    label:
      "What are your thoughts on the company growth? Increased/decreased growth going forward?",
    description: "Company growth",
    category: "Financial Analysis",
    link: "https://www.google.com/search?q=",
    position: 1,
    type: "text",
  },
  {
    label:
      "Is the company making a profit and are the profit margins increasing over time? If the margins are low, where's the money being spent?",
    description: "Profit margin",
    category: "Financial Analysis",
    link: "https://www.google.com/search?q=",
    position: 2,
    type: "text",
  },
  {
    label: "How is the debt situation? Is there any signs of trouble?",
    description: "Debt",
    category: "Financial Analysis",
    link: "https://www.google.com/search?q=",
    position: 3,
    type: "text",
  },
  {
    label: "What is the ratio of immaterial assets? Could this be an issue?",
    description: "Immaterial assets",
    category: "Financial Analysis",
    link: "https://www.google.com/search?q=",
    position: 4,
    type: "text",
  },
  {
    label:
      "How has the cash-flow been used in the last few years? Does the CEO plan for coming cash-flow usage?",
    description: "Cash-flow",
    category: "Financial Analysis",
    link: "https://www.google.com/search?q=",
    position: 5,
    type: "text",
  },
  {
    label:
      "Is there an efficient usage of assets to generate profits? Does it increase over time?",
    description: "Efficiency/profitability",
    category: "Financial Analysis",
    link: "https://www.google.com/search?q=",
    position: 6,
    type: "text",
  },
  {
    label:
      "How's the profitability of company rivals? What could explain the differences?",
    description: "Competitor profitability",
    category: "Financial Analysis",
    link: "https://www.google.com/search?q=",
    position: 7,
    type: "text",
  },
  {
    label: "Is the valuation attractive? Buy/Hold/Sell?",
    description: "Buy/Hold/Sell",
    category: "Financial Analysis",
    link: "https://www.google.com/search?q=",
    position: 8,
    type: "text",
  },
  {
    label:
      "Is there any macro-economic trends that could affect the company? Present and future?",
    description: "Macro-economics",
    category: "Macro",
    link: "https://www.google.com/search?q=",
    position: 1,
    type: "text",
  },
  {
    label: "Is the company currently affected by events in the world? How?",
    description: "Current events",
    category: "Macro",
    link: "https://www.google.com/search?q=",
    position: 2,
    type: "text",
  },
  {
    label:
      "Why is the company a good fit for the Pillow portfolio? Is it a good complement to current assets?",
    description: "Portfolio-fit",
    category: "Portfolio-fit",
    link: "https://www.google.com/search?q=",
    position: 1,
    type: "text",
  },
]
