export const BASE = [
  {
    label: "Company Name",
    description: "Write the name of the company",
    category: "info",
    position: 1,
    type: "text",
  },
  {
    label: "Company Description",
    description: "Write a short description of the company",
    category: "info",
    position: 2,
    type: "textarea",
  },
  {
    label: "Sector",
    description: "For example banking, industry or commerce",
    category: "info",
    position: 3,
    type: "text",
  },
  {
    label: "Line of business",
    description:
      "For example internet banking, industrial machines or ecommerce",
    category: "info",
    position: 4,
    type: "text",
  },
  {
    label: "List",
    description: "Where can the company be bought?",
    category: "info",
    position: 5,
    type: "text",
  },
  {
    label: "Ticker",
    description: "For example GOOG or TSLA",
    category: "info",
    position: 6,
    type: "text",
  },
  {
    label: "Market Cap (MSEK)",
    description: "The total company value",
    category: "values",
    position: 1,
    type: "number",
  },
  {
    label: "Stock Price",
    description: "How the market values the company",
    category: "values",
    position: 2,
    type: "number",
  },
  {
    label: "Stock Currency",
    description: "What currency the stock is traded in",
    category: "values",
    position: 3,
    type: "text",
  },
  {
    label: "P/E",
    description: "Price / Earnings (Earning power)",
    category: "valuation",
    position: 1,
    type: "number",
  },
  {
    label: "P/S",
    description: "Price / Sales (Growth and size)",
    category: "valuation",
    position: 2,
    type: "number",
  },
  {
    label: "P/B",
    description: "Price / Book (Valuation of assets)",
    category: "valuation",
    position: 3,
    type: "number",
  },
  {
    label: "Yield",
    description: "Return on investment without selling",
    category: "valuation",
    position: 4,
    type: "number",
  },
  {
    label: "What is the company product?",
    description: "How do they earn money?",
    category: "Product & Market",
    position: 1,
    type: "text",
  },
  {
    label: "What is their unique selling point (USP)?",
    description: "Something that differentiates the company from the rest",
    category: "Product & Market",
    position: 2,
    type: "text",
  },
  {
    label: "How big is the market for the product today?",
    description: "Is it a large and stable company?",
    category: "Product & Market",
    position: 3,
    type: "text",
  },
  {
    label:
      "Do you think the market will shrink or grow in the coming five years?",
    description: "Why do you think so?",
    category: "Product & Market",
    position: 4,
    type: "text",
  },
  {
    label: "Who are the biggest competitors on the market?",
    description: "Are they bigger or smaller than the company?",
    category: "Product & Market",
    position: 5,
    type: "text",
  },
]
